<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>1561da55-e7cb-494a-99fb-a893af194fda</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Neo4j.Driver" Version="6.3.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
